# App related configuration
# [app]
# timeout = 30
# oldest = 3600
# ticker = 30
# loglevel = "INFO"
# branding_disabled = false

# A Discord webhook
[[webhooks]]
name = "Hook-1"
url = "https://discord.com/api/webhooks/XXX/YYY"

# A RSS or Atom feed
[[feeds]]
name = "NYT"
url = "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml"
webhooks = ["Hook-1"]
# disabled = false